<?php

return [
    // The Telegram BOT api token
    'token' => env('TELEGRAM_TOKEN'),

    // Telegram-IP-range validation for webhook mode. MUST stay off: prod sits
    // behind Cloudflare + a local Caddy hop, so REMOTE_ADDR is never a
    // Telegram IP and safe_mode silently drops every update (bot goes mute
    // while Telegram still sees 2xx). Authentication is handled by the
    // X-Telegram-Bot-Api-Secret-Token check in VerifyTelegramWebhook instead.
    'safe_mode' => false,

    // Extra or specific configurations
    'config' => [],

    // Set if the service provider should automatically load
    // handlers from /routes/telegram.php
    'routes' => true,

    // Enable or disable Nutgram mixins
    'mixins' => false,

    // Path to save files generated by nutgram:make command
    'namespace' => app_path('Telegram'),

    // Set log channel
    'log_channel' => env('TELEGRAM_LOG_CHANNEL', 'null'),
];
